import { Colors } from "@blueprintjs/core";

export const COLOR_THEMES = {
    COBALT: [
        Colors.COBALT1,
        Colors.COBALT2,
        Colors.COBALT3,
        Colors.COBALT4,
        Colors.COBALT5,
    ],
    BLUE: [
        Colors.BLUE1,
        Colors.BLUE2,
        Colors.BLUE3,
        Colors.BLUE4,
        Colors.BLUE5,
    ],
    DARK_GRAY: [
        Colors.DARK_GRAY1,
        Colors.DARK_GRAY2,
        Colors.DARK_GRAY3,
        Colors.DARK_GRAY4,
        Colors.DARK_GRAY5,
    ],
    FOREST: [
        Colors.FOREST1,
        Colors.FOREST2,
        Colors.FOREST3,
        Colors.FOREST4,
        Colors.FOREST5,
    ],
    GOLD: [
        Colors.GOLD1,
        Colors.GOLD2,
        Colors.GOLD3,
        Colors.GOLD4,
        Colors.GOLD5,
    ],
    GRAY: [
        Colors.GRAY1,
        Colors.GRAY2,
        Colors.GRAY3,
        Colors.GRAY4,
        Colors.GRAY5,
    ],
    GREEN: [
        Colors.GREEN1,
        Colors.GREEN2,
        Colors.GREEN3,
        Colors.GREEN4,
        Colors.GREEN5,
    ],
    INDIGO: [
        Colors.INDIGO1,
        Colors.INDIGO2,
        Colors.INDIGO3,
        Colors.INDIGO4,
        Colors.INDIGO5,
    ],
    LIGHT_GRAY: [
        Colors.LIGHT_GRAY1,
        Colors.LIGHT_GRAY2,
        Colors.LIGHT_GRAY3,
        Colors.LIGHT_GRAY4,
        Colors.LIGHT_GRAY5,
    ],
    LIME: [
        Colors.LIME1,
        Colors.LIME2,
        Colors.LIME3,
        Colors.LIME4,
        Colors.LIME5,
    ],
    ORANGE: [
        Colors.ORANGE1,
        Colors.ORANGE2,
        Colors.ORANGE3,
        Colors.ORANGE4,
        Colors.ORANGE5,
    ],
    RED: [
        Colors.RED1,
        Colors.RED2,
        Colors.RED3,
        Colors.RED4,
        Colors.RED5,
    ],
    ROSE: [
        Colors.ROSE1,
        Colors.ROSE2,
        Colors.ROSE3,
        Colors.ROSE4,
        Colors.ROSE5,
    ],
    SEPIA: [
        Colors.SEPIA1,
        Colors.SEPIA2,
        Colors.SEPIA3,
        Colors.SEPIA4,
        Colors.SEPIA5,
    ],
    TURQUOISE: [
        Colors.TURQUOISE1,
        Colors.TURQUOISE2,
        Colors.TURQUOISE3,
        Colors.TURQUOISE4,
        Colors.TURQUOISE5,
    ],
    VERMILION: [
        Colors.VERMILION1,
        Colors.VERMILION2,
        Colors.VERMILION3,
        Colors.VERMILION4,
        Colors.VERMILION5,
    ],
    VIOLET: [
        Colors.VIOLET1,
        Colors.VIOLET2,
        Colors.VIOLET3,
        Colors.VIOLET4,
        Colors.VIOLET5,
    ],
};
